version: '3.8'

services:
  splunk:
    image: splunk/splunk:latest
    container_name: nodeheim_test_splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
      - SPLUNK_PASSWORD=Password123
      - SPLUNK_LICENSE_URI=Free
    ports:
      - "8000:8000"
      - "8089:8089"
      - "9997:9997"
    volumes:
      - ./:/opt/splunk/etc/apps/nodeheim:rw