version: '3.8'

services:
  splunk:
    image: splunk/splunk:latest
    container_name: nodeheim_test_splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
      - SPLUNK_PASSWORD=Password123
      - SPLUNK_USER=splunk
      - SPLUNK_GROUP=splunk
      - SPLUNK_HOME=/opt/splunk
      - SPLUNK_ROLE=splunk_standalone
      - ACCEPT_LICENSE=true
      - SPLUNK_ENABLE_LISTEN=9997
    ports:
      - "8000:8000"
      - "8089:8089"
      - "9997:9997"
    volumes:
      - ./:/opt/splunk/etc/apps/nodeheim:rw
    healthcheck:
      test: ["CMD", "/opt/splunk/bin/splunk", "status", "--accept-license", "--answer-yes", "--no-prompt"]
      interval: 10s
      timeout: 5s
      retries: 3