version: '3.8'

services:
  splunk:
    image: splunk/splunk:latest
    container_name: nodeheim_test_splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
      - SPLUNK_PASSWORD=Password123
      - SPLUNK_HOME=/opt/splunk
      - ACCEPT_LICENSE=true
    ports:
      - "8000:8000"
      - "8089:8089"
    volumes:
      - ./:/opt/splunk/etc/apps/nodeheim:rw
    user: root
    command: >
      sh -c "
        chown -R splunk:splunk /opt/splunk &&
        su -s /bin/bash splunk -c '/opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt &&
        /opt/splunk/bin/splunk cmd python3 -m pip install python-nmap psutil &&
        /opt/splunk/bin/splunk restart'
      "